kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-api-pod
        image: woodregistry.azurecr.io/smilr/frontend
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: acr-auth
